app:
    app_name: "Transparent-Framework"
    app_logging_level: 'INFO'
    app_random_seed: 0

    # DIRS STRUCTURE
    ROOT_DIR: "/transparent-framework/"             # Root directory of the framework.
    DATA_DIR: "/data/"                              # Data directory of the framework.

jobs:
    job_list:                                       # If not running an experiment, you can run individual training, testing job.
        # - "create_city_state"
        # - "build_regression_models"
        # - "fill_sparse_matrices"
        # - "export_neighborhood_data"
        - "run_experiments"
        # - "run_rl_training"
        # - "run_rl_testing"

experiments:                                        # Experiments to be conducted.
    expt_list:
        - "experiment_00"                   
        # - "experiment_01"
        # - "experiment_02"
        # - "experiment_03"
        # - "experiment_04"
        # - "experiment_05"
        # - "experiment_06"
        # - "experiment_07"
        # - "experiment_08"

city_state_creator:
    start_time: "2015-09-02 00:00:00"               # Start time of the city states file.
    end_time: "2015-09-08 23:59:59"                 # End time of the city states file.
    time_slice_duration: 5                          # Each time slice duration (keep = time slice duration for this work).
    time_unit_duration: 5                           # Each time unit (5 mins = 288 time slices in a 24 hour day).
    business_days:
        - "Monday" 

        # - "Tuesday"
        #
        # - "Wednesday"
        #
        # - "Thursday"
        #
        # - "Friday"
        #
        # - "Saturday"
        #
        # - "Sunday"
    business_hours_start: 0                     # Used to create a city states file over a week but for example, only 8-5 each day.
    business_hours_end: 23          

regression_models:                              # Create Stata-usable dataset from the raw data for linear regression models.
    # - year: "2015"
    #   month: "September" 
    #   weekday: "Sunday"

    - year: "2015"
      month: "September" 
      weekday: "Monday"

    # - year: "2015"
    #   month: "September" 
    #   weekday: "Tuesday"

    # - year: "2015"
    #   month: "September" 
    #   weekday: "Wednesday"

    # - year: "2015"
    #   month: "September" 
    #   weekday: "Thursday"

    # - year: "2015"
    #   month: "September" 
    #   weekday: "Friday"

    # - year: "2015"
    #   month: "September" 
    #   weekday: "Saturday"

RL_parameters:
    experiment: "expt"                          # Experiment name if running a training job.
    # RL training parameters
    city_states_filename: "city_states.dill"    # City states file used to train the model.
    objective: "revenue"                        # Set to 'pickups' if you wish to optimize for demand fulfillment.
    allow_coordination: True                    # Set to False if to disable coordinated learning.
    discount_factor: 0.99
    learning_rate: 0.01
    ind_episodes: 160
    reb_episodes: 60
    num_episodes: 200
    # Driver section.
    num_drivers: 6000
    num_strategic_drivers: 6000                 # If less than total drivers, the remaining drivers are naive.
    driver_distribution: "uniform"              # Uniform distribution at time t=0
    imbalance_threshold: 2                      # Imbalance threhsold used during rebalancing
    exp_decay_multiplier: 3                     # Decay exponent for exploration rate
    # Output section.
    # Provide the filenames if you wish to output the corresponding 
    # model, episode or overall training process details.
    best_model_filename: False 
    best_episode_filename: False
    training_tracker_filename: False

Model_testing:
    experiment: "expt_00_test"                  # Experiment name if running a training job.
    model_filename: "expt_00.dill"              # Model to use for deployment.
    city_states_filename: "city_states.dill"    # City states file to deploy the model on.
